import {getSessionSecret,verifyRoleRequest,secretEqual,getOwnerSecret} from './security.js';
const STEP_COOKIE='__Host-tti_owner_stepup',enc=new TextEncoder();let settingsReady=false;
function b64url(buf){let s='';for(const b of new Uint8Array(buf))s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function getCookie(req,name){const raw=req.headers.get('cookie')||'';for(const p of raw.split(';')){const i=p.indexOf('=');if(i<0)continue;if(p.slice(0,i).trim()===name)return p.slice(i+1).trim()}return''}
async function hmac(secret,msg){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(msg)))}
export async function ensureRuntimeSettings(db){if(!db)throw new Error('runtime_store_unavailable');if(settingsReady)return;await db.exec(`CREATE TABLE IF NOT EXISTS owner_runtime_settings(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL,updated_by TEXT NOT NULL DEFAULT 'owner');`);settingsReady=true}
export async function getRuntimeSetting(env,key,fallback=''){const db=env.ANALYTICS_DB;if(!db)return fallback;try{await ensureRuntimeSettings(db);const row=await db.prepare(`SELECT value FROM owner_runtime_settings WHERE key=?`).bind(key).first();return row?.value??fallback}catch(e){return fallback}}
export async function setRuntimeSetting(env,key,value,by='owner'){const db=env.ANALYTICS_DB;if(!db)throw new Error('runtime_store_unavailable');await ensureRuntimeSettings(db);await db.prepare(`INSERT INTO owner_runtime_settings(key,value,updated_at,updated_by) VALUES(?,?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at,updated_by=excluded.updated_by`).bind(String(key),String(value),new Date().toISOString(),String(by)).run()}
export async function runtimeEnabled(env,key,fallback=true){const v=await getRuntimeSetting(env,key,fallback?'1':'0');return !['0','false','off'].includes(String(v).toLowerCase())}
export async function issueOwnerStepUp(env){const secret=getSessionSecret(env);if(!secret)throw new Error('session_secret_missing');const exp=Date.now()+300000,nonce=crypto.randomUUID().replace(/-/g,''),base=`v1.${exp}.${nonce}`,sig=b64url(await hmac(secret,base));return{expiresAt:new Date(exp).toISOString(),cookie:`${STEP_COOKIE}=${base}.${sig}; Path=/; Max-Age=300; HttpOnly; Secure; SameSite=Strict; Priority=High`}}
export function clearOwnerStepUp(){return `${STEP_COOKIE}=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict; Priority=High; Expires=Thu, 01 Jan 1970 00:00:00 GMT`}
export async function verifyOwnerStepUp(req,env){const secret=getSessionSecret(env);if(!secret)return false;const p=getCookie(req,STEP_COOKIE).split('.');if(p.length!==4||p[0]!=='v1')return false;const exp=Number(p[1]),nonce=p[2],sig=p[3];if(!Number.isFinite(exp)||exp<Date.now()||exp>Date.now()+360000)return false;if(!/^[a-f0-9]{32}$/i.test(nonce)||!/^[A-Za-z0-9_-]{32,64}$/.test(sig))return false;const expected=b64url(await hmac(secret,`v1.${exp}.${nonce}`));return await secretEqual(sig,expected)}
export async function verifyOwnerCritical(req,env){const owner=await verifyRoleRequest(req,env,['owner']);if(!owner.ok)return{ok:false,status:owner.role==='admin'?403:401,error:owner.role==='admin'?'owner_required':'unauthorized'};if(!(await verifyOwnerStepUp(req,env)))return{ok:false,status:428,error:'reauth_required'};return{ok:true,role:'owner'}}
export async function verifyOwnerToken(token,env){const secret=getOwnerSecret(env);return !!secret&&await secretEqual(String(token||''),secret)}
