let schemaReady=false;
const BASE_SCHEMA=`CREATE TABLE IF NOT EXISTS analytics_events(id INTEGER PRIMARY KEY AUTOINCREMENT,created_at TEXT NOT NULL,day_jakarta TEXT NOT NULL,event_type TEXT NOT NULL,path TEXT NOT NULL,label TEXT NOT NULL DEFAULT '',session_id TEXT NOT NULL DEFAULT '');CREATE INDEX IF NOT EXISTS idx_analytics_day ON analytics_events(day_jakarta);CREATE INDEX IF NOT EXISTS idx_analytics_type_day ON analytics_events(event_type,day_jakarta);CREATE INDEX IF NOT EXISTS idx_analytics_path_type ON analytics_events(path,event_type);`;
const EXTRA_COLUMNS={country:"TEXT NOT NULL DEFAULT ''",region:"TEXT NOT NULL DEFAULT ''",city:"TEXT NOT NULL DEFAULT ''",continent:"TEXT NOT NULL DEFAULT ''",cf_timezone:"TEXT NOT NULL DEFAULT ''",device_type:"TEXT NOT NULL DEFAULT ''",browser:"TEXT NOT NULL DEFAULT ''",os:"TEXT NOT NULL DEFAULT ''",referrer_host:"TEXT NOT NULL DEFAULT ''",source:"TEXT NOT NULL DEFAULT ''",medium:"TEXT NOT NULL DEFAULT ''",landing_path:"TEXT NOT NULL DEFAULT ''",approx_lat:"REAL",approx_lon:"REAL",gps_lat:"REAL",gps_lon:"REAL",gps_accuracy:"REAL",gps_permission:"TEXT NOT NULL DEFAULT ''"};
const COOKIE='__Host-tti_admin';
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex'}})}
async function ready(db){if(schemaReady)return;await db.exec(BASE_SCHEMA);const info=await db.prepare('PRAGMA table_info(analytics_events)').all(),present=new Set((info.results||[]).map(r=>r.name));for(const[n,t]of Object.entries(EXTRA_COLUMNS)){if(!present.has(n))await db.exec(`ALTER TABLE analytics_events ADD COLUMN ${n} ${t};`)}await db.exec(`CREATE INDEX IF NOT EXISTS idx_analytics_geo ON analytics_events(country,region,city);CREATE INDEX IF NOT EXISTS idx_analytics_source ON analytics_events(source,medium);CREATE INDEX IF NOT EXISTS idx_analytics_device ON analytics_events(device_type,browser,os);CREATE INDEX IF NOT EXISTS idx_analytics_landing ON analytics_events(landing_path);CREATE INDEX IF NOT EXISTS idx_analytics_coords ON analytics_events(approx_lat,approx_lon);`);schemaReady=true}
function jktDay(o=0){return new Date(Date.now()+7*3600000+o*86400000).toISOString().slice(0,10)}
function getCookie(req,name){const raw=req.headers.get('cookie')||'';for(const p of raw.split(';')){const i=p.indexOf('=');if(i<0)continue;if(p.slice(0,i).trim()===name)return p.slice(i+1).trim()}return''}
function safeEq(a,b){a=String(a||'');b=String(b||'');if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
function b64url(buf){let s='';for(const b of new Uint8Array(buf))s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function sign(secret,msg){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64url(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(msg)))}
async function isAdmin(req,secret){const header=String(req.headers.get('x-stats-token')||'');if(header&&safeEq(header,secret))return true;const raw=getCookie(req,COOKIE),parts=raw.split('.');if(parts.length!==3||parts[0]!=='v1')return false;const exp=Number(parts[1]);if(!Number.isFinite(exp)||exp<Date.now())return false;const base=`v1.${exp}`,expected=await sign(secret,base);return safeEq(parts[2],expected)}
function hint(s){return 'ANON-'+String(s||'').replace(/-/g,'').slice(0,6).toUpperCase()}
export async function onRequest(context){
  if(context.request.method!=='GET')return json({ok:false,error:'method_not_allowed'},405);
  const db=context.env.ANALYTICS_DB;if(!db)return json({ok:false,error:'analytics_db_not_configured',setup:true},503);
  const u=new URL(context.request.url),wantPrivate=u.searchParams.get('private')==='1',secret=String(context.env.STATS_TOKEN||'');
  if(wantPrivate&&!secret)return json({ok:false,error:'stats_token_not_configured',adminSetup:true},503);
  if(wantPrivate&&!(await isAdmin(context.request,secret)))return json({ok:false,error:'unauthorized'},401);
  try{
    await ready(db);const today=jktDay(),start=jktDay(-13);
    if(wantPrivate){const cutoff=new Date(Date.now()-7*86400000).toISOString();await db.prepare("UPDATE analytics_events SET gps_lat=NULL,gps_lon=NULL,gps_accuracy=NULL WHERE gps_lat IS NOT NULL AND created_at < ?").bind(cutoff).run()}
    const queries=[
      db.prepare(`SELECT COUNT(*) events,COUNT(DISTINCT CASE WHEN session_id<>'' THEN session_id END) active_sessions,SUM(event_type='page_view') page_views,SUM(event_type='calculate') calculations,SUM(event_type='copy_result') copies,SUM(event_type='article_open') articles,SUM(event_type='calculator_open') tool_opens,COUNT(DISTINCT CASE WHEN country<>'' THEN country END) countries,SUM(event_type='geo_granted') gps_grants FROM analytics_events WHERE day_jakarta=?`).bind(today).first(),
      db.prepare(`SELECT COUNT(*) events,COUNT(DISTINCT CASE WHEN session_id<>'' THEN session_id END) sessions,SUM(event_type='page_view') page_views,SUM(event_type='calculate') calculations,SUM(event_type='copy_result') copies,SUM(event_type='article_open') articles,SUM(event_type='geo_granted') gps_grants FROM analytics_events`).first(),
      db.prepare(`SELECT path,MAX(label) label,COUNT(*) uses FROM analytics_events WHERE event_type='calculate' GROUP BY path ORDER BY uses DESC LIMIT 10`).all(),
      db.prepare(`SELECT path,MAX(label) label,COUNT(*) views FROM analytics_events WHERE event_type='article_open' GROUP BY path ORDER BY views DESC LIMIT 10`).all(),
      db.prepare(`SELECT day_jakarta day,COUNT(DISTINCT CASE WHEN session_id<>'' THEN session_id END) sessions,SUM(event_type='page_view') page_views,SUM(event_type='calculate') calculations,SUM(event_type='copy_result') copies,SUM(event_type='article_open') articles,SUM(event_type='calculator_open') tool_opens FROM analytics_events WHERE day_jakarta>=? GROUP BY day_jakarta ORDER BY day_jakarta`).bind(start).all(),
      db.prepare(`SELECT country,COUNT(DISTINCT session_id) sessions FROM analytics_events WHERE country<>'' AND session_id<>'' GROUP BY country ORDER BY sessions DESC LIMIT 10`).all(),
      db.prepare(`SELECT country,region,city,COUNT(DISTINCT session_id) sessions FROM analytics_events WHERE city<>'' AND session_id<>'' GROUP BY country,region,city ORDER BY sessions DESC LIMIT 10`).all(),
      db.prepare(`SELECT device_type name,COUNT(DISTINCT session_id) sessions FROM analytics_events WHERE device_type<>'' AND session_id<>'' GROUP BY device_type ORDER BY sessions DESC LIMIT 10`).all(),
      db.prepare(`SELECT browser name,COUNT(DISTINCT session_id) sessions FROM analytics_events WHERE browser<>'' AND session_id<>'' GROUP BY browser ORDER BY sessions DESC LIMIT 10`).all(),
      db.prepare(`SELECT os name,COUNT(DISTINCT session_id) sessions FROM analytics_events WHERE os<>'' AND session_id<>'' GROUP BY os ORDER BY sessions DESC LIMIT 10`).all(),
      db.prepare(`SELECT source,medium,MAX(referrer_host) referrer_host,COUNT(DISTINCT session_id) sessions FROM analytics_events WHERE source<>'' AND session_id<>'' GROUP BY source,medium ORDER BY sessions DESC LIMIT 12`).all(),
      db.prepare(`SELECT landing_path path,COUNT(DISTINCT session_id) sessions FROM analytics_events WHERE landing_path<>'' AND session_id<>'' GROUP BY landing_path ORDER BY sessions DESC LIMIT 10`).all(),
      db.prepare(`SELECT label term,COUNT(*) searches FROM analytics_events WHERE event_type='site_search' AND label<>'' GROUP BY label ORDER BY searches DESC LIMIT 10`).all(),
      db.prepare(`SELECT created_at,event_type,path,label FROM analytics_events ORDER BY id DESC LIMIT 24`).all()
    ];
    const[tr,ar,tools,articles,daily,countries,cities,devices,browsers,oses,sources,landing,searches,recent]=await Promise.all(queries);
    const out={ok:true,timezone:'Asia/Jakarta',generatedAt:new Date().toISOString(),privacy:{rawIpStored:false,identityStored:false,fullReferrerStored:false,networkCoordinatesRounded:true,preciseGpsOptIn:true,preciseGpsRetentionDays:7},today:tr||{},allTime:ar||{},topTools:tools.results||[],topArticles:articles.results||[],daily:daily.results||[],countries:countries.results||[],cities:cities.results||[],devices:devices.results||[],browsers:browsers.results||[],operatingSystems:oses.results||[],sources:sources.results||[],landingPages:landing.results||[],internalSearches:searches.results||[],recent:recent.results||[],geoPrivate:false};
    if(wantPrivate){
      const[approx,gps,consent,sessions]=await Promise.all([
        db.prepare(`SELECT approx_lat lat,approx_lon lon,MAX(city) city,MAX(region) region,MAX(country) country,COUNT(DISTINCT session_id) sessions FROM analytics_events WHERE approx_lat IS NOT NULL AND approx_lon IS NOT NULL GROUP BY approx_lat,approx_lon ORDER BY sessions DESC LIMIT 120`).all(),
        db.prepare(`SELECT session_id,gps_lat lat,gps_lon lon,gps_accuracy accuracy,created_at,city,region,country,source,device_type FROM analytics_events WHERE event_type='geo_granted' AND gps_lat IS NOT NULL AND gps_lon IS NOT NULL ORDER BY id DESC LIMIT 100`).all(),
        db.prepare(`SELECT gps_permission permission,COUNT(*) count FROM analytics_events WHERE gps_permission<>'' GROUP BY gps_permission ORDER BY count DESC`).all(),
        db.prepare(`SELECT session_id,MIN(created_at) first_seen,MAX(created_at) last_seen,MAX(country) country,MAX(region) region,MAX(city) city,MAX(device_type) device_type,MAX(browser) browser,MAX(os) os,MAX(source) source,MAX(medium) medium,MAX(landing_path) landing_path,COUNT(*) events,SUM(event_type='page_view') page_views,SUM(event_type='calculate') calculations,MAX(CASE WHEN event_type='geo_granted' THEN 1 ELSE 0 END) gps_opt_in FROM analytics_events WHERE session_id<>'' GROUP BY session_id ORDER BY MAX(id) DESC LIMIT 50`).all()
      ]);
      out.geoPrivate=true;out.networkPoints=approx.results||[];out.precisePoints=(gps.results||[]).map(r=>({...r,sessionHint:hint(r.session_id),session_id:undefined}));out.geoConsent=consent.results||[];out.visitorSessions=(sessions.results||[]).map(r=>({sessionHint:hint(r.session_id),first_seen:r.first_seen,last_seen:r.last_seen,country:r.country,region:r.region,city:r.city,device_type:r.device_type,browser:r.browser,os:r.os,source:r.source,medium:r.medium,landing_path:r.landing_path,events:r.events,page_views:r.page_views,calculations:r.calculations,gps_opt_in:r.gps_opt_in}));
    }
    return json(out)
  }catch(e){return json({ok:false,error:'stats_error'},500)}
}
