
const MODEL="@cf/google/gemma-4-26b-a4b-it",MAX_BODY=2600000,MAX_IMAGE_DATA_URL=2050000;
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store, max-age=0","X-Robots-Tag":"noindex","Referrer-Policy":"no-referrer"}})}
function clean(v,max=1200){return String(v||"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,max)}
function parseDataUrl(x){const m=String(x||"").match(/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=\s]+)$/i);if(!m)return null;let bin;try{bin=atob(m[2].replace(/\s/g,""))}catch(e){return null}const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return{mime:m[1].toLowerCase(),bytes}}
function textOf(r){if(!r)return"";if(typeof r==="string")return r;if(typeof r.response==="string")return r.response;if(typeof r.result==="string")return r.result;if(typeof r.text==="string")return r.text;const c=r.choices?.[0]?.message?.content;if(typeof c==="string")return c;if(Array.isArray(c))return c.map(x=>x?.text||x?.content||"").join("\n");return""}
function parseJsonLoose(t){let s=String(t||"").trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"").trim();try{return JSON.parse(s)}catch(e){}const a=s.indexOf("{"),b=s.lastIndexOf("}");if(a>=0&&b>a)try{return JSON.parse(s.slice(a,b+1))}catch(e){}return null}
function num(v){if(v===null||v===undefined||v==="")return null;const n=Number(String(v).replace(",","."));return Number.isFinite(n)?n:null}
function normalize(raw){
 raw=raw&&typeof raw==="object"?raw:{};const o=raw.object&&typeof raw.object==="object"?raw.object:{},d=raw.extracted_data&&typeof raw.extracted_data==="object"?raw.extracted_data:{},a=raw.assessment&&typeof raw.assessment==="object"?raw.assessment:{},r=raw.resistor&&typeof raw.resistor==="object"?raw.resistor:{};
 const risk=["info","caution","high"].includes(String(a.risk_level||"").toLowerCase())?String(a.risk_level).toLowerCase():"info";
 return{report_title:clean(raw.report_title,140)||"AI Visual Engineering Report",object:{name:clean(o.name,160)||"Belum dapat dipastikan",category:clean(o.category,60)||"general",confidence_percent:Math.max(0,Math.min(100,num(o.confidence_percent)??0)),alternatives:Array.isArray(o.alternatives)?o.alternatives.slice(0,5).map(x=>clean(x,120)).filter(Boolean):[]},observations:Array.isArray(raw.observations)?raw.observations.slice(0,12).map(x=>clean(x,220)).filter(Boolean):[],extracted_text:clean(raw.extracted_text,2200),extracted_data:{manufacturer:clean(d.manufacturer,120),model_number:clean(d.model_number,120),voltage_v:num(d.voltage_v),current_a:num(d.current_a),power_w:num(d.power_w),power_va:num(d.power_va),frequency_hz:num(d.frequency_hz),phase:clean(d.phase,30),power_factor:num(d.power_factor),rpm:num(d.rpm),capacitance_uf:num(d.capacitance_uf),resistance_ohm:num(d.resistance_ohm),capacity_btu_h:num(d.capacity_btu_h),capacity_pk:num(d.capacity_pk),dimensions_text:clean(d.dimensions_text,160)},resistor:{applicable:!!r.applicable,bands:Array.isArray(r.bands)?r.bands.slice(0,6).map(x=>clean(x,30).toLowerCase()).filter(Boolean):[],tolerance_percent:num(r.tolerance_percent),watt_estimate:clean(r.watt_estimate,80),note:clean(r.note,260)},assessment:{summary:clean(a.summary,1200),risk_level:risk,possible_issues:Array.isArray(a.possible_issues)?a.possible_issues.slice(0,10).map(x=>clean(x,240)).filter(Boolean):[]},safety_notes:Array.isArray(raw.safety_notes)?raw.safety_notes.slice(0,10).map(x=>clean(x,240)).filter(Boolean):[],recommendations:Array.isArray(raw.recommendations)?raw.recommendations.slice(0,12).map(x=>clean(x,240)).filter(Boolean):[],follow_up_questions:Array.isArray(raw.follow_up_questions)?raw.follow_up_questions.slice(0,10).map(x=>clean(x,240)).filter(Boolean):[]}
}
function resistorVerified(report){
 if(!report.resistor?.applicable)return;
 const names=report.resistor.bands.map(x=>x.replace(/abu-?abu/g,"grey").replace(/cokelat/g,"brown").replace(/merah/g,"red").replace(/oranye/g,"orange").replace(/kuning/g,"yellow").replace(/hijau/g,"green").replace(/biru/g,"blue").replace(/ungu/g,"violet").replace(/hitam/g,"black").replace(/putih/g,"white").replace(/emas/g,"gold").replace(/perak/g,"silver"));
 const digit={black:0,brown:1,red:2,orange:3,yellow:4,green:5,blue:6,violet:7,grey:8,white:9},mult={black:1,brown:10,red:100,orange:1000,yellow:10000,green:100000,blue:1000000,violet:10000000,grey:100000000,white:1000000000,gold:.1,silver:.01},tol={brown:1,red:2,green:.5,blue:.25,violet:.1,grey:.05,gold:5,silver:10};
 if(names.length>=4&&digit[names[0]]!==undefined&&digit[names[1]]!==undefined&&mult[names[2]]!==undefined){const v=((digit[names[0]]*10)+digit[names[1]])*mult[names[2]];report.extracted_data.resistance_ohm=v;report.resistor.tolerance_percent=tol[names[3]]??report.resistor.tolerance_percent??null;report.resistor.verified_value=v>=1e6?`${Number((v/1e6).toFixed(3))} MΩ`:v>=1e3?`${Number((v/1e3).toFixed(3))} kΩ`:`${Number(v.toFixed(3))} Ω`}
}
function verifiedCalculations(report){
 const d=report.extracted_data||{},out=[],V=num(d.voltage_v),I=num(d.current_a),pf=num(d.power_factor),phase=String(d.phase||"").toLowerCase();
 if(V!==null&&I!==null&&V>0&&I>0){if(phase.includes("3")){const S=Math.sqrt(3)*V*I;out.push({name:"Apparent power 3-phase",formula:"S = √3 × V × I",result:`≈ ${Number(S.toFixed(1))} VA`,note:"Tidak memasukkan power factor."});if(pf!==null&&pf>0&&pf<=1)out.push({name:"Active power 3-phase",formula:"P = √3 × V × I × PF",result:`≈ ${Number((S*pf).toFixed(1))} W`,note:"Berdasarkan PF yang terbaca."})}else{const S=V*I;out.push({name:"Apparent power",formula:"S = V × I",result:`≈ ${Number(S.toFixed(1))} VA`,note:"Watt nyata dapat berbeda karena PF/efisiensi."});if(pf!==null&&pf>0&&pf<=1)out.push({name:"Active power 1-phase",formula:"P = V × I × PF",result:`≈ ${Number((S*pf).toFixed(1))} W`,note:"Berdasarkan PF yang terbaca."})}}
 return out
}
const SYSTEM=`Anda adalah AI Vision milik Teknisi Tools Indonesia untuk intake engineering/technician.
Analisis foto teknis dan konteks pengguna secara konservatif. Bedakan antara yang benar-benar terlihat dan inferensi.
Jangan mengarang rating, ukuran, bahan, kerusakan, model, tegangan, arus, kapasitas, atau nilai jika tidak terlihat jelas.
Untuk panel listrik, refrigerant, struktur, gas, pressure system, mesin berputar, atau bagian berbahaya: beri safety note dan jangan memberi instruksi berisiko.
Untuk resistor: baca gelang warna hanya jika cukup jelas. Jangan memastikan watt hanya dari foto kecuali ada skala/dimensi pembanding yang nyata.
Untuk nameplate: salin marking secara hati-hati dan gunakan null untuk angka yang tidak jelas.
Return HANYA JSON valid tanpa markdown:
{"report_title":"string","object":{"name":"string","category":"electrical|hvac|civil|plumbing|electronics|mechanical|maintenance|automation|general","confidence_percent":0,"alternatives":[]},"observations":[],"extracted_text":"string","extracted_data":{"manufacturer":"","model_number":"","voltage_v":null,"current_a":null,"power_w":null,"power_va":null,"frequency_hz":null,"phase":"","power_factor":null,"rpm":null,"capacitance_uf":null,"resistance_ohm":null,"capacity_btu_h":null,"capacity_pk":null,"dimensions_text":""},"resistor":{"applicable":false,"bands":[],"tolerance_percent":null,"watt_estimate":"","note":""},"assessment":{"summary":"string","risk_level":"info|caution|high","possible_issues":[]},"safety_notes":[],"recommendations":[],"follow_up_questions":[]}`;
async function direct(ai,img,prompt){return await ai.run(MODEL,{messages:[{role:"system",content:SYSTEM},{role:"user",content:[{type:"text",text:prompt},{type:"image_url",image_url:{url:img}}]}],max_tokens:1800,temperature:.12,chat_template_kwargs:{enable_thinking:false}},{rejectIfBusy:true})}
async function fallback(ai,parsed,prompt){const c=await ai.toMarkdown({name:`upload.${parsed.mime.split("/")[1]||"jpg"}`,blob:new Blob([parsed.bytes],{type:parsed.mime})},{conversionOptions:{output:{format:"text"}}}),one=Array.isArray(c)?c[0]:c,vision=one?.data||"";const response=await ai.run(MODEL,{messages:[{role:"system",content:SYSTEM},{role:"user",content:`IMAGE DESCRIPTION / OCR DARI VISION PIPELINE:\n${clean(vision,7000)}\n\nUSER CONTEXT:\n${prompt}`}],max_tokens:1800,temperature:.12,chat_template_kwargs:{enable_thinking:false}},{rejectIfBusy:true});return response}
export async function onRequest(context){
 const req=context.request;if(req.method==="GET")return json({ok:true,configured:!!context.env.AI,model:MODEL,storage:false});if(req.method==="OPTIONS")return new Response(null,{status:204,headers:{Allow:"GET, POST, OPTIONS"}});if(req.method!=="POST")return json({ok:false,error:"method_not_allowed"},405);if(!context.env.AI)return json({ok:false,error:"ai_binding_not_configured",message:"Tambahkan Workers AI binding bernama AI pada Cloudflare Pages project."},503);
 const u=new URL(req.url),origin=req.headers.get("origin");if(origin&&origin!==u.origin)return json({ok:false,error:"cross_origin_forbidden"},403);if(Number(req.headers.get("content-length")||0)>MAX_BODY)return json({ok:false,error:"payload_too_large"},413);
 let data;try{const raw=await req.text();if(raw.length>MAX_BODY)return json({ok:false,error:"payload_too_large"},413);data=JSON.parse(raw)}catch(e){return json({ok:false,error:"invalid_json"},400)}
 const imageDataUrl=String(data.imageDataUrl||"");if(imageDataUrl.length>MAX_IMAGE_DATA_URL)return json({ok:false,error:"image_too_large"},413);const parsed=parseDataUrl(imageDataUrl);if(!parsed)return json({ok:false,error:"invalid_image"},400);
 const mode=clean(data.mode,40)||"smart_report",category=clean(data.category,50)||"general",question=clean(data.question,1200),note=clean(data.note,1200),localOcr=clean(data.localOcr,2200);
 const prompt=`MODE: ${mode}\nKATEGORI PILIHAN USER: ${category}\nPERTANYAAN USER: ${question||"Identifikasi objek/komponen, jelaskan fungsi, data penting yang terlihat, risiko, dan rekomendasi teknis."}\nCATATAN CUSTOMER: ${note||"-"}\nOCR LOKAL (bisa salah): ${localOcr||"-"}\nBuat Smart Report dalam bahasa Indonesia. Jangan menjadikan OCR lokal sebagai fakta jika bertentangan dengan foto.`;
 try{let source="direct_multimodal",resp;try{resp=await direct(context.env.AI,imageDataUrl,prompt)}catch(e){resp=await fallback(context.env.AI,parsed,prompt);source="toMarkdown_fallback"}let parsedJson=parseJsonLoose(textOf(resp));if(!parsedJson)parsedJson={report_title:"AI Visual Engineering Report",object:{name:"Objek teknis dari foto",category,confidence_percent:40,alternatives:[]},observations:[],extracted_text:"",extracted_data:{},resistor:{applicable:false,bands:[],tolerance_percent:null,watt_estimate:"",note:""},assessment:{summary:clean(textOf(resp),1200)||"Respons model tidak terstruktur.",risk_level:"caution",possible_issues:[]},safety_notes:["Verifikasi dengan nameplate, pengukuran, manual produsen, dan inspeksi lapangan."],recommendations:["Coba foto close-up yang lebih fokus bila informasi masih kurang."],follow_up_questions:[]};const report=normalize(parsedJson);resistorVerified(report);return json({ok:true,model:MODEL,vision_source:source,report,verified_calculations:verifiedCalculations(report),privacy:{storedBySite:false,sentToAnalytics:false}})}
 catch(e){const m=String(e?.message||e||"");if(/capacity|3040|429/i.test(m))return json({ok:false,error:"ai_capacity_busy",message:"AI sedang penuh. Coba lagi beberapa saat."},429);if(/allocation|3036/i.test(m))return json({ok:false,error:"ai_daily_allocation_exceeded",message:"Kuota AI harian Cloudflare sudah habis."},429);return json({ok:false,error:"ai_inference_error",message:"AI Vision gagal memproses gambar."},500)}
}
